#!/bin/zsh

# AppleのNTPサーバーから時刻情報を取得
date_info=`sntp time.asia.apple.com`

# 端末時刻と取得した時刻の差分を抽出
RETVAL=`echo "$date_info"  | sed '1d'| sed -E "s/^.*\).+(\+|\-)([0-9]+)\..*$/\2/"`

# 差分が10秒程度？より大きければエラー
if [[ $RETVAL -gt 10 ]]; then
  printf "\e[31m 端末の時間を戻してください!! \e[m\n"
  exit 1
else
  exit 0
fi
